---
title: "Single cell gene correlation with neuropathology markers"
---

About this site


```{r goi-corr-data}
goi_corr <- load_or_placeholder(
  option_name = "results_vis.goi_corr",
  pattern = "genes.*(interest|goi).*corr.*\\.(csv|tsv|txt|rds|rda|RData|xlsx)$",
  generator = function() {
    genes <- paste0("Gene", LETTERS[1:10])
    metrics <- paste0("Metric", 1:10)
    expand_grid(Gene = genes, Metric = metrics) %>%
      mutate(Correlation = runif(n(), min = -1, max = 1))
  }
)
```

```{r goi-corr-plot}
render_source_note(goi_corr, "genes of interest correlation")
goi_wide <- goi_corr %>%
  tidyr::pivot_wider(names_from = Metric, values_from = Correlation)
goi_matrix <- goi_wide %>%
  column_to_rownames("Gene") %>%
  as.matrix()
goi_hover <- goi_corr %>%
  mutate(label = glue::glue("{Gene} vs {Metric}<br>Correlation: {round(Correlation, 2)}")) %>%
  tidyr::pivot_wider(names_from = Metric, values_from = label) %>%
  column_to_rownames("Gene") %>%
  as.matrix()
plot_ly(
  x = colnames(goi_matrix),
  y = rownames(goi_matrix),
  z = goi_matrix,
  type = "heatmap",
  colors = "RdBu",
  reversescale = TRUE,
  text = goi_hover,
  hoverinfo = "text"
) %>%
  layout(title = "Genes of Interest Correlation Matrix") %>%
  annotate_placeholder(goi_corr)
```
